before_install:
  - sudo apt-get install -y curl cmake

addons:
  apt:
    update: true

language: julia

os: linux
julia: 1.0

before_install:

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("HermiteGF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("HermiteGF")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
